version: "3.8"

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbtest
    ports:
      - 15432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=sigl@eseo.fr
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../symfony-back-api/:/var/www
      - /var/www/var
      - /var/www/vendor

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../symfony-back-api/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"

  node:
    container_name: node
    build:
      context: ./node
    volumes:
      - ./../vue-front-app/:/app
      - /app/node_modules
    ports:
      - "9090:9090"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=1
